user:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

pages_pages:
    resource: "@PagesPagesBundle/Resources/config/routing.yml"
    prefix:   /

bakkerij:
    resource: "@BakkerijBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"