<?php

namespace Bakkerij\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * mediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
}
